name: "Chromatic Publish"

on:
  push:
    branches:
      - main
    paths:
      - "apps/storybook/**"
      - "packages/frey-ui/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - ".github/workflows/chromatic.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: "10.30.0"
      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run build-storybook --filter=@frey-ui/storybook
      - run: test -f apps/storybook/storybook-static/preview-stats.json
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: apps/storybook
          storybookBuildDir: storybook-static
          onlyChanged: true
